---
- name: "Verificar se chave pública já existe"
  stat: path=/home/hadoopuser/.ssh/id_rsa.pub
  register: pub_key_created
  become: yes

- name: "Criar nova chave pública para usuário hadoopuser"
  shell: "{{ item }}"
  loop:
    - ssh-keygen -t rsa -f /home/hadoopuser/.ssh/id_rsa -P ""
  become: yes
  become_user: hadoopuser
  when: pub_key_created.stat.exists == False

# Solução: Copiar chave pública do hadoop-master para os Slaves
# Assim conectar sem necessidade de senha

#- name:
#  shell: ssh-copy-id hadoopuser@{{ item }}
#  loop:
#    - 172.17.177.40
#    - 172.17.177.41
#    - 172.17.177.42
#  become: yes
