---
- name: "Adicionar SSH key dos Slaves no known_hosts do Master"
  shell: ssh-keyscan -H "{{ item }}" >> /home/hadoopuser/.ssh/known_hosts
  with_items:
    - "{{ hadoop_all_hostname_list }}"
  become: yes
  become_user: hadoopuser

- name: "Limpar conteúdo do arquivo workers no Master"
  shell: cat /dev/null > /usr/local/hadoop/etc/hadoop/workers
  become: yes
  become_user: hadoopuser

- name: "Adicionar configuração no arquivo workers no Master"
  ansible.builtin.lineinfile:
    path: /usr/local/hadoop/etc/hadoop/workers
    line: "{{ item }}"
  with_items: "{{ hadoop_slaves_hostname_list }}"
  become: yes
  become_user: hadoopuser

- name: "Copiar arquivo workers do Master para Slaves"
  shell: scp /usr/local/hadoop/etc/hadoop/workers hadoopuser@"{{ item }}":/usr/local/hadoop/etc/hadoop/
  with_items: "{{ hadoop_slaves_hostname_list }}"
  become: yes
  become_user: hadoopuser

- name: "Mudar grupo e usuário proprietário do arquivo workers"
  command: chown hadoopuser:root -R /usr/local/hadoop/etc/hadoop/workers
  become: yes
