Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-18.04"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024 # 1024 de memória
        v.customize [ "modifyvm", :id,
                      "--nicpromisc2", "allow-all"
                    ]
    end

    config.vm.define "hadoop-master" do |hm|
        # Definindo a rede como private e o ip
        hm.vm.network "private_network", ip: "172.17.177.40"
    end

    #config.vm.define "mysql" do |m|
        # Definindo a rede como private e o ip
        #m.vm.network "private_network", ip: "172.17.177.42"
    #end

end
