Vagrant.configure("2") do |config|
    config.vm.box = "hadoop-cluster-box"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024 # 1024 de memória
      v.customize [ "modifyvm", :id,
                  "--nicpromisc2", "allow-all"
                  ]
    end

    config.vm.define "hadoop-master" do |hm|
      hm.vm.hostname = "hadoop-master"
      # Definindo a rede como private e o ip
      hm.vm.network "private_network", ip: "172.17.177.40"
    end

    config.vm.define "hadoop-slave1" do |hs1|
      hs1.vm.hostname = "hadoop-slave1"
      # Definindo a rede como private e o ip
      hs1.vm.network "private_network", ip: "172.17.177.41"
    end

    config.vm.define "hadoop-slave2" do |hs2|
      hs2.vm.hostname = "hadoop-slave2"
      # Definindo a rede como private e o ip
      hs2.vm.network "private_network", ip: "172.17.177.42"
    end

end
