---
- name: "Copiar arquivo de configuração yarn-site.xml para os Slaves"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/hadoop/etc/hadoop/"
    owner: hadoopuser
    group: root
  with_fileglob:
    - "files/*"
  become: yes
