---
- name: 'Instalar pacotes necessários'
  apt:
    name:
      - ssh
      - pdsh
      - openjdk-8-jdk
    state: latest
  become: yes

- name: "Adicionar linha ao arquivo .bashrc"
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bashrc
    line: export PDSH_RCMD_TYPE=ssh

- name: "Verificar se chave pública já existe"
  stat: path=/home/vagrant/.ssh/id_rsa.pub
  register: pub_key_created

- name: "Criar nova chave pública e copiar no authorized_keys"
  shell: "{{ item }}"
  loop:
    - ssh-keygen -t rsa -f /home/vagrant/.ssh/id_rsa -P ""
    - cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  when: pub_key_created.stat.exists == False

- name: "Verificar se a pasta hadoop já existe"
  stat: path=/usr/local/hadoop
  register: hadoop_created

- name: 'Baixar o arquivo de instalação do Hadoop se ainda não existir'
  get_url:
    url: 'https://mirrors.sonic.net/apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz'
    dest: '/tmp/hadoop.tar.gz'
  when: hadoop_created.stat.exists == False

- name: 'Descompactar o arquivo hadoop-3.2.1.tar.gz se ainda não existir'
  unarchive:
    src: '/tmp/hadoop.tar.gz'
    dest: '/usr/local/'
    remote_src: yes
  become: yes
  when: hadoop_created.stat.exists == False

- name: 'Renomeando pasta para apenas hadoop se ainda não existir'
  command: mv /usr/local/hadoop-3.2.1 /usr/local/hadoop
  when: hadoop_created.stat.exists == False
  become: yes

- name: "Incluir JAVA_HOME no arquivo hadoop-env.sh"
  ansible.builtin.lineinfile:
    path: /usr/local/hadoop/etc/hadoop/hadoop-env.sh
    regexp: '^#  JAVA_HOME='
    line: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  become: yes

- name: "Adicionando JAVA_HOME no arquivo environment"
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
  become: yes
