---
- name: "Copiar arquivos de configuração /etc/hosts"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/"
    owner: root
    group: root
  with_fileglob:
    - "files/hosts/*"
  become: yes

- name: "Reiniciando Master e Slaves após configurar hostname"
  reboot:
    reboot_timeout: 90
  become: yes

- name: "Copiar arquivos de configuração Hadoop"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/hadoop/etc/hadoop/"
    owner: hadoopuser
    group: root
  with_fileglob:
    - "files/hadoop/*"
  become: yes

- name: "Adicionar SSH key dos Slaves no known_hosts do Master"
  shell: ssh-keyscan -H "{{ item }}" >> /home/hadoopuser/.ssh/known_hosts
  with_items:
    - "{{ master_slaves_hostname_list }}"
  become: yes
  become_user: hadoopuser

- name: "Verificar se o arquivo authorized_keys já existe"
  stat: path=/home/hadoopuser/.ssh/authorized_keys
  register: authorized_keys_created
  become: yes
  become_user: hadoopuser

- name: "Copiar SSH key para o authorized_keys"
  shell: cat /home/hadoopuser/.ssh/id_rsa.pub >> /home/hadoopuser/.ssh/authorized_keys
  when: authorized_keys_created.stat.exists == False
  become: yes
  become_user: hadoopuser
