---
- name: "Adicionar master e slaves do Hadoop no arquivo hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertbefore: '# The following lines are desirable for IPv6 capable hosts'
    line: "{{ item }}"
  with_items: "{{ hadoop_hostname_list }}"
  become: yes

- name: "Adicionar hostname do master e slaves no arquivo /etc/hostname"
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ ansible_hostname }}"
  become: yes

- name: "Reiniciando Master e Slaves após configurar hostname"
  reboot:
    reboot_timeout: 30
  become: yes

- name: "Aidionar SSH key do hadoopuser nas VMs"
  shell: cat /home/hadoopuser/.ssh/id_rsa.pub >> /home/hadoopuser/.ssh/authorized_keys
  become: yes
  become_user: hadoopuser
